sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: QZ/USCCwmblGEK8rS+2O8hL1V70AyyI7geqSjZLYSTmrc/X6sjvFrRNL+W1PbQr8T3A2+zdiZiUEuh8/MC7ghFtHqj4SoKqO45wSsLPJu86SwVN+CiDYGufONvqowAqymT8GH8t4oZPtXF+c/Rrn4cKZpWm5XtI7FbW2aDHB5YZlKTPFxCtV0XVk+RdwuNSRUW4xVy9PAHbDRD1exwpB7bN6B1TKrrxegaVzOq+7k90GfTdL7VXUuAFU8hscfI+x4TMJcYFaznBK9BDeOVslSieC0BOKq8aE1tpZh9eRjttPf8GpsqRtMvtoKJUaWOL+xT572VOUkJ283IIaOWA8Apx+sqY1XZ/Wokk4meXhfAOJQ7t6jJS7wnEsD4l1fMyRWl9s65aK66wj47wkyn+k1zuUE7/S9Qrpn9ZyCArksU2utEU/8siQTM9Ex9W/Zl9qfwJVuQgI2ORBnplt8RUatOi9oL48EswzmzczMsc9xnCXSAAs9Gqytl8SoL/tB5AZ3Jj5aqN6ezTYEpuauOn9oYby11BwZEjwCsHIZ3diUPT9jZ3aiUIQ1wWWrdckkzMKVPJI//8Fe9uYn83LWg1r6bKnX4C92MtIyKEdDgCCBFsuwGWI6bqzPtks4ckJZYVr0XpAYgZ/wi2Avd2UsHlEcHZNR6n6nXzHSs7VcavAE+w=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Sons-of-the-Soil_1417
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy